disabled_rules:
  - force_cast
  - force_try
  - identifier_name
  - line_length

excluded:
  - .build/
  - Carthage/
  - Example/
  - InstallTests/
  - Tests/
  - build/
  - docs/
  - node_modules/
  - vendor/
