os: osx
language: swift
xcode_project: ApolloDeveloperKit.xcodeproj
xcode_scheme: ApolloDeveloperKit

cache:
  bundler: true

matrix:
  include:
  - name: "Unit Tests: Xcode 10.3 / iOS 12.4 / Apollo 0.19.0"
    osx_image: xcode10.3
    xcode_sdk: iphonesimulator12.4
    xcode_destination: "platform=iOS Simulator,OS=12.4,name=iPhone X"
    env:
      - APOLLO_VERSION=0.19.0
      - SWIFT_VERSION=5.0
  - name: "Unit Tests: Xcode 10.3 / iOS 12.4 / Apollo 0.18.1"
    osx_image: xcode10.3
    xcode_sdk: iphonesimulator12.4
    xcode_destination: "platform=iOS Simulator,OS=12.4,name=iPhone X"
    env:
      - APOLLO_VERSION=0.18.1
      - SWIFT_VERSION=5.0
  - name: "Unit Tests: Xcode 10.2 / iOS 12.2 / Apollo 0.15.3"
    osx_image: xcode10.2
    xcode_sdk: iphonesimulator12.2
    xcode_destination: "platform=iOS Simulator,OS=12.2,name=iPhone X"
    env:
      - APOLLO_VERSION=0.15.3
      - SWIFT_VERSION=5.0
  - osx_image: xcode10.2
    xcode_sdk: iphonesimulator12.2
    xcode_destination: "platform=iOS Simulator,OS=12.2,name=iPhone X"
    env:
      - APOLLO_VERSION=0.14.0
      - SWIFT_VERSION=5.0
    name: "Unit Tests: Xcode 10.2 / iOS 12.2 / Apollo 0.14.0"
  - osx_image: xcode10.2
    xcode_sdk: iphonesimulator12.2
    xcode_destination: "platform=iOS Simulator,OS=12.2,name=iPhone X"
    env:
      - APOLLO_VERSION=0.12.0
      - SWIFT_VERSION=5.0
    name: "Unit Tests: Xcode 10.2 / iOS 12.2 / Apollo 0.12.0"
  - osx_image: xcode10.1
    xcode_sdk: iphonesimulator12.1
    xcode_destination: "platform=iOS Simulator,OS=10.3.1,name=iPhone SE"
    env:
      - APOLLO_VERSION=0.9.5
      - SWIFT_VERSION=4.2
    name: "Unit Tests: Xcode 10.1 / iOS 10.3.1 / Apollo 0.9.5"
  - osx_image: xcode10.1
    install: bundle install --without documentation --jobs=3 --retry=3
    script: |
      echo 'APOLLO_DEVELOPER_KIT_SWIFT_VERSION=4.2' >ApolloDeveloperKit.xcconfig
      XCODE_XCCONFIG_FILE="$PWD/ApolloDeveloperKit.xcconfig" bundle exec make -C InstallTests carthage
    name: "Install Tests: Carthage"
  - osx_image: xcode10.2
    install: bundle install --without documentation --jobs=3 --retry=3
    script: bundle exec pod lib lint --swift-version=5.0 --verbose
    env: COCOAPODS_DISABLE_STATS=true
    name: "Lint podspec"

install:
  - perl -pi -e 's/"[\d.]+"$/"$ENV{APOLLO_VERSION}"/ if /apollographql\/apollo-ios/' Cartfile.resolved
  - ./Scripts/quick-install-dependencies
  - perl -pi -e 's/(?<=APOLLO_DEVELOPER_KIT_SWIFT_VERSION)( *= *)[0-9.]*/${1}$ENV{SWIFT_VERSION}/' Configurations/ApolloDeveloperKit.xcconfig
