os: osx
osx_image: xcode10.1
cache:
  bundler: true
  directories:
    - Carthage/Build
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
  matrix:
    - DESTINATION="OS=12.1,name=iPhone XS"
    - DESTINATION="OS=11.4,name=iPhone 5s"
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - carthage build --platform iOS --no-use-binaries --cache-builds
  - xcodebuild -project ApolloDeveloperKit.xcodeproj -scheme ApolloDeveloperKit -destination "$DESTINATION" -configuration Debug test | xcpretty
  - xcodebuild -project ApolloDeveloperKit.xcodeproj -scheme ApolloDeveloperKitExample -destination "$DESTINATION" -configuration Debug build | xcpretty
