name: Release

on:
  release:
    types: [published]

jobs:
  publish-to-cocoapods:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          gem install bundler -v 1.17.3
          bundle install --without documentation --jobs=3 --retry=3
      - name: Publish to CocoaPods
        run: bundle exec pod trunk push --swift-version=5.1 --verbose ApolloDeveloperKit.podspec
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
          DEVELOPER_DIR: /Applications/Xcode_11.1.app/Contents/Developer
