---
name: Release
on:
  release:
    types:
    - published
jobs:
  publish-to-cocoapods:
    runs-on: macOS-10.15
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      BUNDLE_WITHOUT: documentation:test
      COCOAPODS_TRUNK_TOKEN: "${{ secrets.COCOAPODS_TRUNK_TOKEN }}"
      DEVELOPER_DIR: "/Applications/Xcode_12.app/Contents/Developer"
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: bundle install
    - name: Set up CocoaPods repository
      run: bundle exec pod setup
    - name: Publish to CocoaPods
      run: bundle exec pod trunk push --swift-version=5.3 --verbose ApolloDeveloperKit.podspec
