name: Test

on: [push]

jobs:
  unit-test:
    runs-on: macOS-latest
    strategy:
      fail-fast: false
      matrix:
        apollo: ["0.22.0", "0.19.0", "0.18.1"]
        sdk: ["iphonesimulator", "macosx"]
        include:
          - apollo: "0.22.0"
            sdk: "iphonesimulator"
            xcode: "11.3"
            swift: "5.1"
            destination: "platform=iOS Simulator,OS=13.3,name=iPhone 11"
          - apollo: "0.22.0"
            sdk: "macosx"
            xcode: "11.3"
            swift: "5.1"
            destination: "platform=OS X,arch=x86_64"
          - apollo: "0.19.0"
            sdk: "iphonesimulator"
            xcode: "11.1"
            swift: "5.1"
            destination: "platform=iOS Simulator,OS=13.1,name=iPhone 11"
          - apollo: "0.19.0"
            sdk: "macosx"
            xcode: "11.1"
            swift: "5.1"
            destination: "platform=OS X,arch=x86_64"
          - apollo: "0.18.1"
            sdk: "iphonesimulator"
            xcode: "11"
            swift: "5.1"
            destination: "platform=iOS Simulator,OS=13.0,name=iPhone 11"
          - apollo: "0.18.1"
            sdk: "macosx"
            xcode: "11"
            swift: "5.1"
            destination: "platform=OS X,arch=x86_64"
    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
      - name: Run build script tests
        run: RUBYLIB=lib ruby test/apollo_version_test.rb
      - name: Modify Cartfile.resolved
        run: perl -pi -e 's/"[\d.]+"$/"${{ matrix.apollo }}"/ if /apollographql\/apollo-ios/' Cartfile.resolved
      - name: Install dependencies
        run: ./Scripts/quick-install-dependencies -f '${{ matrix.sdk }}'
      - name: Run unit tests
        run: set -o pipefail && xcodebuild test -project ApolloDeveloperKit.xcodeproj -scheme ApolloDeveloperKit -sdk '${{ matrix.sdk }}' -destination '${{ matrix.destination }}' APOLLO_DEVELOPER_KIT_SWIFT_VERSION=${{ matrix.swift }} | xcpretty
  install-test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_11.1.app/Contents/Developer
      - name: Run install tests
        run: make -C InstallTests carthage
  lint-podspec:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_11.1.app/Contents/Developer
      - name: Install dependencies
        run: |
          gem install bundler -v 1.17.3
          bundle install --without documentation --jobs=3 --retry=3
      - name: Lint podspec
        run: bundle exec pod lib lint --swift-version=5.1 --verbose
  frontend-test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run frontend tests
        run: npm test
