name: CI

on: [push]

jobs:
  frontend-test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm install
      - name: Run frontend tests
        run: npm test
  script-test:
    runs-on: macOS-10.14
    steps:
      - uses: actions/checkout@v1
      - name: Run script tests
        run: ruby test/apollo_version_test.rb
        env:
          RUBYLIB: lib
